### ISSUE TITLE
gi.repository.GLib.Error

### ISSUE THREAD

**Issue by taboopython** [taboopython/mod-coral#3]
$ sh birdfeeder_pycoral.sh
bird_classify_pycoraltest.py:32: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Loading /home/mendel/coral/pycoral/test_data/mobilenet_v2_1.0_224_quant_edgetpu.tflite with /home/mendel/coral/pycoral/test_data/ImageNetLabels.txt labels.
Gstreamer pipeline:  v4l2src device=/dev/video0 ! video/x-raw,width=640,height=480,framerate=30/1 ! queue max-size-buffers=1 leaky=downstream  ! tee name=t
            t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! videoscale ! video/x-raw,format=RGB,width=320,height=180 ! appsink name=appsink sync=false emit-signals=true max-buffers=1 drop=true
            t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert
               ! rsvgoverlay name=overlay ! videoconvert ! ximagesink
            
Traceback (most recent call last):
  File "bird_classify_pycoraltest.py", line 171, in <module>
    main()
  File "bird_classify_pycoraltest.py", line 168, in main
    result = gstreamer.run_pipeline(user_callback)
  File "/home/mendel/coral/project-birdfeeder-master/gstreamer.py", line 94, in run_pipeline
    pipeline = Gst.parse_launch(pipeline)
gi.repository.GLib.Error: gst_parse_error: no element "ximagesink" (1)

**Comment by emingenc** [comment]
I solved with these installs

```
sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-bad gstreamer1.0-tools gstreamer1.0-x
```
